### ISSUE TITLE
a problem about demo_face128.m

### ISSUE THREAD

**Issue by amy6chunxiao** [Yijunmaverick/GenerativeFaceCompletion#11]
I have encountered a problem when I ran the demo_face128.m. 
Error occurs at line 36:  net = caffe.Net(net_model, net_weights, phase); 
It shows that:
Error parsing text-format caffe.NetParameter: 372:18: Message type "caffe.LayerParameter" has no field named "upsample_param".
Is that I failed to compile caffe? but I run make matcaffe and mattest successfully
Do you know how to solve it? Thank you!

**Comment by aaaaaaaak** [comment]
@amy6chunxiao 
Have you solved it?
I have the same problem, can you help me to solve it?
Thanks!

**Comment by amy6chunxiao** [comment]
Yeah, it is because the version of the caffe you are using is not correct, please check if your caffe and matcaffe version are correct and consistent

**Comment by aaaaaaaak** [comment]
但是我目前没有GPU不能安装cudnn 所以不能直接编译作者的版本 请问你有合适的版本分享么

**Comment by amy6chunxiao** [comment]
我的cudnn和作者用的版本不一样，所以只编译了CPU版的，太久没用被我删掉了。
