### ISSUE TITLE
Caffe doesn't declare its version in headers

### ISSUE THREAD

**Issue by lensea** [Yijunmaverick/GenerativeFaceCompletion#2]
@Yijunmaverick  Hi ！See your item , i'm very intresting ! But , i can't build it ! Because of the caffe version is not confirm!!!
 at Setup Introduction
We use the  caffe version v2.5.48. Please refer Caffe for more installation details ！ What's means caffe v2.5.48 ?????

**Comment by Yijunmaverick** [comment]
@lensea Thanks for your interests. Since I add in an "upsample" layer from [SegNet](https://arxiv.org/abs/1511.00561), I found that the way of adding new layers in different versions of Caffe is also slightly different. That's why I provide the version information, in case that you want to add more new layers.

**Comment by lensea** [comment]
Yijunmaverick:
          Hi. When i builded the project ,some errors appeared ! So ,can you tell me how to buil it ? cmake or makefile ? My environment is Linux and GCC5.2.

发自我的 iPhone

**Comment by lensea** [comment]
@Yijunmaverick Thks! I build it .

**Comment by zhaoshengweifeng** [comment]
@lensea I got error too! Can you tell me how you solve it.

**Comment by lensea** [comment]
You can try this version of caffe ( RadekSimkanic/caffe-for-cudnn-v2.5.48). Athor has  corrected this mistake at readme.

**Comment by zhaoshengweifeng** [comment]
@lensea  Thanks .Have u used your picture to test this projects successfully?

**Comment by lensea** [comment]
@zhaoshengweifeng Yes,I have tested the images .But the effects are general , and you need to fine-tune the program

**Comment by zhaoshengweifeng** [comment]
@lensea 可不可以留个私信方式  我弄这个项目一礼拜了  还没跑起来 心力交瘁  谢谢啦

**Comment by zhaoshengweifeng** [comment]
my stupid friend ignore the warning of g++ version. And i solve it. remember change the soft link of g++ to correct version 4.7.

**Comment by lensea** [comment]
@zhaoshengweifeng Congratulations on your ！my email is lensea@163.com
